version: 2.1

orbs:
  github-release: haskell-works/github-release@1.3.3

parameters:
  src-repo-url:
    type: string
    default: https://github.com/themoddersden/windowsgsm.palworld.git
  branch-name:
    type: string
    default: "production"
  common-build-params:
    type: string
    default: "--disable-shared --disable-static"
  release-version:
    type: string
    default: "1.0.0"

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: ubuntu-22.04:latest
    steps:
      - checkout
      - run:
          name: Update apt cache
          command: sudo apt-get update
      - run:
          name: Install dependencies
          command: sudo apt install -y git gcc make awk tar zip unzip curl
      - run:
          name: Clone iperf3
          command: git clone << pipeline.parameters.src-repo-url >> -b << pipeline.parameters.branch-name >>
      - run:
          name: Compute version number
          command: |
            echo 'export IPERF3_BUILD_VERSION="<< pipeline.parameters.branch-name>>-${CIRCLE_BUILD_NUM}-${CIRCLE_SHA1:0:7}"' | tee -a "$BASH_ENV"
      - run:
          name: Compress Project to Zip
          command: zip -r WindowsGSM.Palworld-$IPERF3_BUILD_VERSION.zip *
          working_directory: .
      - persist_to_workspace:
          root: .
          paths:
            - WindowsGSM.Palworld-$IPERF3_BUILD_VERSION.zip
      - store_artifacts:
          path:  ./WindowsGSM.Palworld-$IPERF3_BUILD_VERSION.zip
  
  spell_check:
    docker:
      - image: cspell/cspell:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: sudo apt install -y git gcc make awk tar zip unzip curl
      - run:
          name: Clone iperf3
          command: git clone << pipeline.parameters.src-repo-url >> -b << pipeline.parameters.branch-name >>
      - run:
          name: Spell Check
          command: cspell -c .vscode/.cspell.json --no-must-find-files --no-summary --no-progress --no-must-find-files --no-summary

  make_release:
    executor: github-release/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Compute version number
          command: |
            echo 'export IPERF3_BUILD_VERSION="<< pipeline.parameters.branch-name>>-${CIRCLE_BUILD_NUM}-${CIRCLE_SHA1:0:7}"' | tee -a "$BASH_ENV"
      - github-release/release:
          tag: v<< pipeline.parameters.release-version >>
          title: << pipeline.parameters.release-version >>
          artefacts-folder: .

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - spell_check
      - make_release:
          type: approval
          requires:
            - spell_check
            - build
